app_images/urls.py
from django.urls import path
from . import views


app_name = 'image'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('ranking/', views.image_ranking, name='create'),
    path('', views.image_list, name='list'),
]

app_posts/urls.py
from django.urls import path
from . import views


#app_name = 'app_posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    path('subject/<slug:subject>/', views.PostListView.as_view(), name='post_list_subject'),

    path('mine/',views.ManagePostListView.as_view(),name='manage_post_list'),
    path('create/',views.PostCreateView.as_view(),name='post_create'),
    path('<pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('<pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),

    path('search/', views.post_search, name='post_search'),


    path('post/<int:post_id>/content/<model_name>/create/',views.ContentCreateUpdateView.as_view(),
         name='post_content_create'),
    path('post/<int:post_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(),
         name='post_content_update'),

    path('content/<int:id>/delete/',views.ContentDeleteView.as_view(), name='post_content_delete'),
    path('post/<int:post_id>/', views.PostContentListView.as_view(), name='post_content_list'),

    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),

    #path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

common_project/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

# this is bad hook , it should be fixed later....
# because after password reset, it didn't go back to login page....
#from pages.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    #this is home page common for all apps.....
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('images/', include('app_images.urls', namespace='images')),
    path('post/', include('app_posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this is to upload users media files i.e. images etc.

templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}
<div class="w3-content w3-padding-large w3-margin-top" id="portfolio">
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="w3-image" width="1000" height="500">



<form action="." method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Bookmark it!">
</form>
</div>
{% endblock %}

templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}




<h1>{{ image.title }}</h1>

    {% load thumbnail %}
    {% thumbnail image.image "300" as im %}
        <a href="{{ image.image.url }}">
            <img src="{{ im.url }}" class="image-detail">
        </a>
    {% endthumbnail %}

    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
        <div>
            <span class="count">

                <span class="total">{{ total_likes }}</span>like{{ total_likes|pluralize }}
            </span>
            <span class="count">
                {{ total_views }} view{{ total_views|pluralize }}
            </span>
            <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
            {% if request.user not in users_like %}
                Like
            {% else %}
                Unlike
            {% endif %}
            </a>
        </div>
        {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
        {% for user in image.users_like.all %}
            <div>
                <img src="{% if user.profile.photo.url %} {{ user.profile.photo.url }} {% endif %}" class="w3-circle" style="height:80px;width:80px" alt="Avatar">
                <p>{{ user.username }}</p>
            </div>
        {% empty %}
        Nobody likes this image yet.
        {% endfor %}
    </div>
    {% endwith %}
{% endblock %}


{% block domready %}
$('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },

      function(data){

        console.log(data);

        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');
          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ?
          'Unlike' :'Like');
          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
        }
      }
    );
});
{% endblock %}

templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
<br>
<br>
<div class="w3-center">
<h1>Images bookmarked</h1>
</div>
<div id="image-list">
{% include "images/image/list_ajax.html" %}
</div>
{% endblock %}






{% block domready %}
var page = 1;
var empty_page = false;
var block_request = false;
$(window).scroll(function() {
var margin = $(document).height() - $(window).height() - 200;
if ($(window).scrollTop() > margin && empty_page == false &&
block_request == false) {
block_request = true;
page += 1;
$.get('?page=' + page, function(data) {
if(data == '') {
empty_page = true;
}
else {
block_request = false;
$('#image-list').append(data);
}
});
}
});
{% endblock %}

templates/images/image/list_ajax.html
{% load thumbnail %}





{% load thumbnail %}

<div class="w3-row-padding w3-margin-top w3-theme-l5">
{% for image in images %}
<div class="w3-third">
  <div class="w3-card">
      <a href="{{ image.get_absolute_url }}">

          {% thumbnail image.image "500x300" crop="100%" as im %}

                <img src="{{ im.url }}" style="width:100%">

          {% endthumbnail %}
      </a>
      <div class="w3-container">
          <h4>{{ image.title }} <span class="w3-right">likes</span><span class="w3-tag w3-theme-l1 w3-right" >{{ image.total_likes }} </span > </h4>
      </div>
  </div>
 <br>
</div>

{% endfor %}
</div>

templates/images/image/ranking.html
{% extends "base.html" %}

{% block title %}Images ranking{% endblock %}

{% block content %}
    <h1>Images ranking with views</h1>
    <ol>
        {% for key, value in most_viewed_ranking.items %}
        <li>
            <a href="{{ image.get_absolute_url }}">
                {{ key }}, {{ value}} views, image_id:{{ key.id }}
            </a>
        </li>
        {% endfor %}
    </ol>
{% endblock %}