app_images/urls.py
from django.urls import path
from . import views


app_name = 'image'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('ranking/', views.image_ranking, name='create'),
    path('', views.image_list, name='list'),
]

app_posts/urls.py
from django.urls import path
from . import views


#app_name = 'app_posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    path('subject/<slug:subject>/', views.PostListView.as_view(), name='post_list_subject'),

    path('mine/',views.ManagePostListView.as_view(),name='manage_post_list'),
    path('create/',views.PostCreateView.as_view(),name='post_create'),
    path('<pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('<pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),

    path('search/', views.post_search, name='post_search'),


    path('post/<int:post_id>/content/<model_name>/create/',views.ContentCreateUpdateView.as_view(),
         name='post_content_create'),
    path('post/<int:post_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(),
         name='post_content_update'),

    path('content/<int:id>/delete/',views.ContentDeleteView.as_view(), name='post_content_delete'),
    path('post/<int:post_id>/', views.PostContentListView.as_view(), name='post_content_list'),

    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),

    #path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
]

common_project/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

# this is bad hook , it should be fixed later....
# because after password reset, it didn't go back to login page....
#from pages.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    #this is home page common for all apps.....
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('images/', include('app_images.urls', namespace='images')),
    path('post/', include('app_posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this is to upload users media files i.e. images etc.

templates/base.html
{% load staticfiles %}



<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" href="{% static 'css/470_font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/w3-theme-blue-grey.css' %}">

<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Lato", sans-serif}
input{padding:8px;display:block;border:none;border-bottom:1px solid #ccc;width:100%}
a{text-decoration: none;}

/* messages */
ul.messages {
    margin:10px 100px;
    padding:0;
    list-style-type:
    none;
}
ul.messages li.success,
ul.messages li.warning,
ul.messages li.error,
ul.messages li.info {
    margin:0;
    padding:14px 20px;
    list-style:none;
    color:#fff;
}

ul.messages li.success { background:#81ce81; }
ul.messages li.success a { color:#0ac33e; }

ul.messages li.error { background:#a30029; color:#e9828e; }
ul.messages li.error a { color:#e9828e; }

ul.messages li.info { background:#faffae; color:#696b4e; }
ul.messages li.info a { color:#1586de; }

ul.messages li.warning { background:#de9404; }
ul.messages li.warning a { color:#f49000; }

ul.messages li a.close {
    margin:0;
    float:right;
    opacity:1;
    border:0;
    box-shadow:none;
    text-shadow:none;
}
</style>

<!-- hero images style -->
{% block style %}
{% endblock style %}



  <title>{% block title %}title to be here{% endblock %}</title>
</head>



{% block bodystyle %}
<body class="w3-theme-l5">
{% endblock %}

<!-- Navbar -->
<div class="w3-top">
 <div class="w3-bar w3-theme-l1 w3-left-align w3-large">

   <a href="{% url 'home'%}" class="w3-bar-item w3-button w3-padding-large"><i class="fa fa-home w3-margin-right"></i><b>StormBooster</b></a>
  {% if request.user.is_authenticated %}
   <a href="{% url 'images:list' %}"  class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white {% if section == 'images' %} w3-theme-d4 {% endif %}">Images</a>
   <a href="{% url 'user_list' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white {% if section == 'people' %} w3-theme-d4 {% endif %}">People</a>
   <a href="{% url 'post_list'%}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white {% if section == 'posts' %} w3-theme-d4 {% endif %}">Posts New</a>


   <div class="w3-dropdown-hover w3-hide-small {% if section == 'dashboard' %} w3-theme-d4 {% endif %}">
    <button class="w3-button w3-padding-large w3-text-blue" title="Notifications">Hello,{{ user.username }}!</button>
    <div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
      <a href="{% url 'dashboard'%}" class="w3-bar-item w3-button">My dashboard</a>
      <a href="{% url 'password_change'%}" class="w3-bar-item w3-button">Change Password</a>
      <a href="{% url 'password_reset'%}" class="w3-bar-item w3-button">Reset your password</a>
      <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-teal">LogOut</a>
    </div>
   </div>
  <div class="w3-dropdown-hover w3-hide-small">
    <button class="w3-button w3-padding-large" title="Notifications"><i class="fa fa-bell"></i><span class="w3-badge w3-right w3-small w3-green">3</span></button>
    <div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
      <a href="#" class="w3-bar-item w3-button">One new Message</a>
      <a href="#" class="w3-bar-item w3-button">25 new comments on your Post</a>
      <a href="#" class="w3-bar-item w3-button">34 new likes on your images</a>
    </div>
  </div>
   <a href="{% url 'post_search' %}" class="w3-bar-item w3-padding-large w3-hover-red w3-hide-small"><i class="fa fa-search"></i></a>






   <a href="#" class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white" title="My Account"><img src="{% if user.profile.photo %} {{ user.profile.photo.url }} {% endif %}" class="w3-circle" style="height:25px;width:25px" alt="Avatar"></a>
  {% else %}
    <a href="{% url 'login' %}" class="w3-button w3-hide-small w3-bar-item w3-teal w3-right w3-padding-large">LogIn</a>
    <a href="{% url 'signup' %}" class="w3-button w3-hide-small w3-bar-item w3-teal w3-right w3-padding-large">SignUp</a>
  {% endif %}
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>

 </div>
</div>



{% if user.profile.photo %} {{ user.profile.photo.url }} {% endif %}



<!-- Navbar on small screens -->
<br><br>
<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
  {% if request.user.is_authenticated %}
  <a href="{% url 'home'%}" class="w3-text-blue w3-bar-item w3-button w3-padding-large">Hello,{{ user.username }}!</a>
  <a href="" class="w3-bar-item w3-button w3-padding-large w3-text-red">Search</a>
  <a href="#" class="w3-bar-item w3-button w3-padding-large">My dashboard</a>
  <a href="{% url 'password_reset'%}" class="w3-bar-item w3-button w3-padding-large">Passwd reset</a>
  <a href="{% url 'password_change'%}" class="w3-bar-item w3-button w3-padding-large">Passwd change</a>
  <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-padding-large w3-teal">LogOut</a>
  {% else %}
  <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-padding-large w3-teal">LogIn</a>
  <a href="{% url 'signup' %}" class="w3-bar-item w3-button w3-padding-large w3-teal">SignUp</a>
  {% endif %}
</div>


<!-- Alert Box -->
{% if messages %}
      <br><br>
      <ul class="messages w3-container w3-center w3-display-container w3-round w3-border w3-theme-border w3-margin-bottom w3-hide-small">
        <span onclick="this.parentElement.style.display='none'" class="w3-button w3-theme-d4 w3-right">
          <i class="fa fa-remove"></i>
        </span>

         {% for message in messages %}
              <li class="{{ message.tags }}">
                  <h2><strong>{{ message|safe }}</strong></h2>
              </li>
         {% endfor %}

      </ul>
{% endif %}


<!-- Content will go here -->
 {% block content %}
Here w3content to be inserted....
{% endblock content %}




<!-- Footer -->
<footer class="w3-container w3-theme-d3 w3-padding-16 w3-center">
  <h5>Footer</h5>
</footer>

<footer class="w3-container w3-theme-d5 w3-center">
  <p>Powered by <a href="default.html" target="_blank">w3.css</a></p>
</footer>

<script src="http://127.0.0.1:8000/static/js/jquery-331.min.js"></script>
<script src="http://127.0.0.1:8000/static/js/js.cookie.min.js"></script>
<script src="http://127.0.0.1:8000/static/js/jquery-ui.min.js"></script>
  <script>

    console.log('hello');

    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    console.log('before domready function');

    $(document).ready(function(){
        console.log('entered block domready');
        {% block domready %}
        {% endblock domready %}
    });
  </script>
  <script>
// Accordion
function myFunction(id) {
    var x = document.getElementById(id);
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
        x.previousElementSibling.className += " w3-theme-d1";
    } else {
        x.className = x.className.replace("w3-show", "");
        x.previousElementSibling.className =
        x.previousElementSibling.className.replace(" w3-theme-d1", "");
    }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>


<script>
// Toggle between hiding and showing post replies/comments
//document.getElementById("myBtn").click();
function hideBlogCommentsFunction(id) {
    var x = document.getElementById(id);
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}

// Toggle between hiding and showing post replies/comments by style:block or none
//document.getElementById("myBtn").click();
function hideBlogCommentsFunctionByStyle(id) {
    var x = document.getElementById(id);
    if (x.style.display == "none") {
        x.style.display = "block";
    } else {
        x.style.display = 'none';
    }
}



function likeFunction(x) {
    x.style.fontWeight = "bold";
    x.innerHTML = "✓ Liked";
}
</script>
<script>
function onClick(element) {
  document.getElementById("img01").src = element.id;
  document.getElementById("modal01").style.display = "block";
}
</script>


</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
{% load static %}

<div class="w3-container w3-center">
  <br>
  <br>
  <br>
  <h1>This is Home page content.</h1>
  <br>
  <br>
    <br>
  <br>
    <br>
  <br>
    <br>
  <br>
    <br>
  <br>
    <br>
  <br>
    <br>
  <br>
    <br>
  <br>
    <br>
  <br>
    <br>
  <br>
</div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<div class="w3-container w3-center">
<h2>Sign Up</h2>
<div class="w3-container">
<form class="w3-container w3-card-4 w3-center w3-input" method="post">
    {% csrf_token %}
    {{ user_form|crispy }}
    <p><button class="w3-button w3-blue" type="submit">Sign Up</button></p>
</form>
</div>
<br><br><br><br><br><br>
</div>
<br><br><br><br><br><br>
{% endblock content %}